apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: todo
type: Opaque
data:
    POSTGRES_USER: ENC[AES256_GCM,data:V2RDoshz,iv:sQm7fcamgNcXgkgb0G5+QF4LeP0KezxbDR+NaQVte8w=,tag:ekcagmoMRcoP4aITwbJr6w==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Ob/iEPQlqQ==,iv:3bJx9cQy0Xxf6l9KQDIuQkbX1Epx3Ia0xbB4N+MJ/xk=,tag:MDX/sln3Ek/Oi8gofC6dbg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:GVX1wA==,iv:tqJfAh1wgFCFZWHdjSIKRu2jSTKfDpxRWFhi+Ifs5Vo=,tag:8KsGgVZUGt51kucaFOPU2Q==,type:str]
sops:
    age:
        - recipient: age1u4734ftpappz96hvtsaahms62d00gmw60ufapsugxtr4jacdfccsrtuv4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERmFIWkJPR3hHbk1XR1V5
            RmRkY2J0MlNPVkJBRVc0MGdXUTlScHR0YkF3CmF3Zmh2WFZBWWVJRXU2cXppQWFO
            LzhDN1BINmkvS05QcXlFUkV4SU9jajgKLS0tIGVKcXNmWWwwWXk1cnRMVHJ4Q3hv
            WmFtK0JYS29zdHlSNEFtcm9DUlhreWsK5eYSduIXGAIejTDwHi1fScOnhhMecunb
            IkzNzzSUOs/TBOs7hPhRcK2FF9l0drjVYqp3V/mg/Ia30ELjx6xWyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T15:51:48Z"
    mac: ENC[AES256_GCM,data:V+dfNyiO3ScwaKyvRSUoEjyLLYTB38Tk2EXWKz56dcpdDpPNCOKD1cV57YbnB2HUCg+MJHhOarUo9zHXKJUSpsO0nXdLjwkmzX8x7LvDf8RSLMi0qNnGY69FrSI0qBpkCdEqeYyj1/Kg0M0rIOMkduRbkPaiugUG2eLX8NGC2x8=,iv:NbeC0pjH5kfBjGs7c6hWRUg7ucj0KayMp3MDxhwQo1Q=,tag:4iYxlH3TzSaihidgIJs9Pg==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
