apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: log-output-app-config
  namespace: log-pong
spec:
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 1
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /healthz
    port: 3000
