apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-app
  template:
    metadata:
      labels:
        app: log-output-app
    spec:
      containers:
        - name: log-writer-app
          image: zanaad/log-writer-app:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
        - name: log-reader-app
          image: zanaad/log-reader-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"