apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-app
  template:
    metadata:
      labels:
        app: log-output-app
    spec:
      volumes:
        - name: shared-log-volume
          emptyDir: {}
      containers:
        - name: log-writer-app
          image: zanaad/log-writer-app:latest
          volumeMounts:
            - name: shared-log-volume
              mountPath: /var/log/shared
          env:
            - name: LOG_FILE
              value: "/var/log/shared/log.txt"

        - name: log-reader-app
          image: zanaad/log-reader-app:latest
          volumeMounts:
            - name: shared-log-volume
              mountPath: /var/log/shared
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: LOG_FILE
              value: "/var/log/shared/log.txt"
