apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-output-app-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: log-output-app-service
                port:
                  number: 3000
          - path: /pingpong
            pathType: Prefix
            backend:
              service:
                name: ping-pong-app-svc
                port:
                  number: 3000