apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gateway.yaml
- route.yaml
- deployment.yaml
- service.yaml
- backendconfig.yaml
- configmap.yaml
images:
- name: READER_IMAGE
  newName: zanaad/log-reader-app
  newTag: 9eae1e6ae9bf6930c47afe12e4b64e74f1cb4af8
- name: WRITER_IMAGE
  newName: zanaad/log-writer-app
  newTag: 9eae1e6ae9bf6930c47afe12e4b64e74f1cb4af8
