apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway.yaml
  - route.yaml
  - deployment.yaml
  - service.yaml
  - backendconfig.yaml
  - configmap.yaml
images:
  - name: READER_IMAGE
    newName: zanaad/log-reader-app
    newTag: latest
  - name: WRITER_IMAGE
    newName: zanaad/log-writer-app
    newTag: latest