apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: log-output-route
  namespace: log-pong
spec:
  parentRefs:
    - name: log-output-gateway
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: log-output-app-svc
          port: 3000
    - matches:
      - path:
          type: PathPrefix
          value: /pingpong    
      backendRefs:
        - name: ping-pong-app-svc
          port: 3000