apiVersion: v1
kind: Service
metadata:
  name: log-output-app-svc
  namespace: log-pong
spec:
  type: ClusterIP
  selector:
    app: log-output-app
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP