apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml
  - postgres-stset.yaml
  - postgres-svc.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: zanaad/todo-backend
    newTag: latest