apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
type: Opaque
data:
    POSTGRES_USER: ENC[AES256_GCM,data:0xG/FO0VCkg=,iv:aei5eBMgjwVNm8LFTvUYnCMkX+QVR8GpWxJl8VeimKw=,tag:bxeL8mA2ctek8Ej3KB9V4A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:BD6ZrkmzBPSqsnf5,iv:FEbtjrjlXlHZzIeI4R9ZZDxc7WdgFl39WKPKcjA4nqg=,tag:i7au3XR5TqEdlILxk4WSQQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:K2ONEv8E5tSYH2Gg,iv:qjzUVVqLmGAR4lHQQtEdqBN79cQEgKuBbB9tB2j8n1g=,tag:6S/Pj63Mua7I3vGMjf7rmg==,type:str]
sops:
    age:
        - recipient: age1rkksvgwtq0jfyv5v98kz0md4emddt9u8xyprxzeqtkzskvqm83wql7lszx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1S1dTZjhXdEZMbUFKL0Y0
            MmcyQmlNWHF4eFkrZ0RqRzhDcFBySHN3QTJBCkVsbnVXeURjeEltWHNWSk5qUG5B
            dHFNZkZqYjhvZ1NaRGJ2MW1SY3c2WncKLS0tIFFMQU9FcFU2T2dzeXZyTGRMQVRP
            dEZuZzlDbTVNVWFNVndvMXdmZjRiNWMK1UUfW23QlL9TVPuGKifz2XD3guZaQHv1
            abbk/x3Z+7h7zGesOnzoM3i+LpnpCFjJrYnb3aJJlTKpAHN7hWRbyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T19:13:41Z"
    mac: ENC[AES256_GCM,data:rePrGA9qCrEjrftE1y1S0wCLp7hrv3Bbn/R7ktdcGsPCgjFQiX8Jp+jCf6rMo3ipCRB4VXdXmjDDhEZohECCX2+hSlJ0iT1/fXKmxetetGy2HTxps81euNFF+guapwIbGQ3FBKGPReTA0wa7q0xkMSQQ3C10BqPghioF/ZIaRtI=,iv:+J2MDHG9RnKaxJYaq1Vh2wjEhLANmM5Up8k72x1gvFk=,tag:Uy3N0rkfvMeeVNFgIO8lXw==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
