apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
type: Opaque
data:
    POSTGRES_USER: ENC[AES256_GCM,data:GdGABcaLhQs=,iv:BSEKu+DMzIZ8biy6Y8vosg4swvVH1K0xY3QlR9Dux/o=,tag:Vz6AaGhUCwQuStC7tyXRHQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:T/UJlyQwQR/dteKj,iv:P+sQ2qCCDRbOtC42vwQC4V+BBjrJViNPSa95YqFaBZM=,tag:GpDGywY7jJp8KsHMlk0AaA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:UYRTJr9SzV0=,iv:BMEx3mZjQYk55O69ah6+fobJZdKDm8hbHQrnaV63aZk=,tag:5tGJyFdzhBrVixD5h0xgBA==,type:str]
sops:
    age:
        - recipient: age1rkksvgwtq0jfyv5v98kz0md4emddt9u8xyprxzeqtkzskvqm83wql7lszx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZkZlWXFYUEMyTDN6MFVC
            YkhZbUNYMHlpMGVqTDZTZ2FLZlk3eVp1RHgwCjBWemF2STArZVZQblZlZGlJL2p5
            QmxWOCtwMHRTdjJNWUlLN0pZZ1hNdEkKLS0tIFNuKzRET1dmZ0Zpc0psQmpOYUVP
            Qi9rM2FlbTlOZ0ZwN2VPdXY2bURHcVEKIcNcdJ64FdbCmpMhJ8rNyFiwfOarixrg
            /g/33BbNE7ZhTd5bzkNfwh5xmDseQEFQBcojjJQWECyMXXbjLWZ+Qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T15:14:29Z"
    mac: ENC[AES256_GCM,data:4SRh4e+zBL+6Ua1wwnw6yixwayw42FmY93fPn7TytYRSjigtEUyDEqupD2ZAdjQLWWNG7grTzxzWzq0wiqqkRx1WI8MJvaT83Liu/+9rArMrFOk1MVTQmnFTTp8S74SEq9CLhDdR5TCBnzuKLttZpCn/iSF1vJ0R4Kui3J2rTW4=,iv:SmLcrkw4gBRpvdu6qVEcUmPq/4mlKOffbAKsZ5fIIzE=,tag:/zSSVxVzu8XVx5rqYC4/Nw==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
