apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: todo
type: Opaque
data:
    POSTGRES_USER: ENC[AES256_GCM,data:NnaF1eS0oJo=,iv:fYtKTVlUBfnyiofoQirdEafIT3ChVIrYXD+nrQpXrVE=,tag:fWycmB8P6HEh/vu7zX7WtA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:/EBXBa8K8jy3uud/,iv:f5N/lMc+NA4UaWKNEjcdSjyfO3mPJyYvOYpQlRmHufY=,tag:4gKskYWek4urhUrI4WSVWg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:CjQVpMpTuzLRO9kU,iv:ZBDLXNNNaH6hdSCVC5ZlI6d/FIPHD00aWbNNE+UZU/E=,tag:C4jEDLworCmITnGlKXo5cw==,type:str]
sops:
    age:
        - recipient: age1rkksvgwtq0jfyv5v98kz0md4emddt9u8xyprxzeqtkzskvqm83wql7lszx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsYW5zbFZkMHVtblE3VjJ1
            N3ZpdmJ6aWN2cDJGRC83WEk5M1JBRG1ZMVZJCjNRK3VhZ0xTdFlmbEllM1hrSU1K
            UlJnMlNGZ2NscTJOcXlaNE40WXZmY2MKLS0tIFBSR09LeXJDMlNlOWZjUmQxT3Qy
            M1F6cmJYVXg3NXVqSzZMMTllOEMxdkUKVxQmydmJy2imRd2CWyFBmk2rVW6QciUr
            W58RzGc9KZEhPrE1Np6urwYmEftPD6eLNKFhuwFVQqnzTojOfVEWig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T21:54:06Z"
    mac: ENC[AES256_GCM,data:j+V/bFMmqMUDPLUckpIFZ0hFTFf3Ah5xnWyC9Q1CdOWyxTWyGn6Ik/k9FVRPfEeAkz1xgQrqNSwnc92ZeDMEozT1MQGz9SFH3fgzYOB16N5tP3kGCeNmU9JPUZZCPoyPsUChX2MJ7swo643MrAM5vEIS1fBdfNSfeXF+j74sYNU=,iv:7f+Y8cI1q4pUIaKcDUzrrh3odr12ldttYSGUH9mUPcs=,tag:C3aZ0g57V6uA84Q8LeqhOg==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
