apiVersion: batch/v1 
kind: CronJob
metadata:
  name: todo-cronjob
  namespace: todo
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-cronjob
              image: zanaad/todo-cronjob:latest
          restartPolicy: OnFailure