apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- todo-backend/k8s
- todo-app/k8s
- todo-job/k8s
- broadcaster/k8s
images:
- name: BROADCASTER_IMAGE
  newName: europe-west3-docker.pkg.dev/dwk-gke-485813/todo-project/broadcaster
  newTag: main-0db48ee4e128a812f172b0ac17185d5320c22edc
- name: TODO_APP_IMAGE
  newName: europe-west3-docker.pkg.dev/dwk-gke-485813/todo-project/todo-app
  newTag: main-0db48ee4e128a812f172b0ac17185d5320c22edc
- name: TODO_BACKEND_IMAGE
  newName: europe-west3-docker.pkg.dev/dwk-gke-485813/todo-project/todo-backend
  newTag: main-0db48ee4e128a812f172b0ac17185d5320c22edc
- name: TODO_JOB_IMAGE
  newName: europe-west3-docker.pkg.dev/dwk-gke-485813/todo-project/todo-cronjob
  newTag: main-0db48ee4e128a812f172b0ac17185d5320c22edc
