apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: log-pong
type: Opaque
data:
    POSTGRES_USER: ENC[AES256_GCM,data:touUMs2t,iv:wckgxbc7UbQh8AfYLa6w2Ua7StWgknpQpKCktIwXkeo=,tag:vSFBycSQKdZYA7BgQNzs+Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:cDZuXw7DXA==,iv:zTNydyGpC3wp2AsN7T+ABIsqpVVVRyWPGC/Ejr7nTd8=,tag:bKm900jmNcse3ETSVYWrsQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:27+dAJvsfw==,iv:Qo41AhWRgYsUXIiYoRU03pxMV3cLKDyytEr0Cadn9uE=,tag:xYmeRjpGRCgEVl4Rtn/C9Q==,type:str]
sops:
    age:
        - recipient: age1u4734ftpappz96hvtsaahms62d00gmw60ufapsugxtr4jacdfccsrtuv4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaUhRY0pRMzRYaDdJRGsy
            d1g1NEtYL0RjWDVJY1lCTERrT0IyQmFFK1JvCnc5TEx5MFZOTks1THFwdmJYRU10
            QXFVdml0QUY3NjFQNHMvRUNjeFZRd0EKLS0tIC8rNHV1R0hyN0NhTWFjVzNXbG04
            ZW05VVNaTTJTMEVCU0s0elM4QjlHWjAK7JfSOuoJmZKf6//YulYMVYqzRO4cOHcn
            qIHEEmuOnTB41hyspt+eYsExPbIaDWXbyBDZhCNWkhPAGr6iM9U4ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T15:32:32Z"
    mac: ENC[AES256_GCM,data:PmSOePG9gEzKIQISywVcxjjL2tVdv6oA5VoseGskf62epVhrIYRD1VqJTaLuJMUvdQ2waEHRDg5MBkrd8Hali3yL8WsCoR7H+4dTFIkoKP3pk+qDZJUIlP+XS5ORGLJyjuTKep6aB06gvridpqjjPTEkRrFm5bmEvjK0boUiKis=,iv:Eq/et/byZ4DA/v91jQLky3aEtaSFq8fWTIdgdYmlbFE=,tag:/nbMYc8YNKU2WDvwAhQszA==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
