apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: log-pong
type: Opaque
data:
    POSTGRES_USER: ENC[AES256_GCM,data:Dfz8JybeY4k=,iv:A+0+coQdjHse6O4iDs3iHzcFsfFs1pyOLvsdWS6Fjco=,tag:/USwEk/Z0gR1/xblApB6Cw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:rMI1ijqTO4Bp0CmA,iv:oExmKiYwRlp9cfuoDrS7p5eM9zXeEGZuYOhDTFuUxZQ=,tag:9RwZWSNhbPMFq1qJkuFK9w==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:/jcA0NzLBQ0jEsKB,iv:9sAjx0RS0RMsFmupZWlFMizc6COSiPWyWsq817sCv9Q=,tag:8rE3dXQdK5ky9/w4uYFscg==,type:str]
sops:
    age:
        - recipient: age1rkksvgwtq0jfyv5v98kz0md4emddt9u8xyprxzeqtkzskvqm83wql7lszx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRk1JM2pUSUdBMStXdllK
            VFJHMEZiQ1R2RTNRRkdQKzAvNlJ5RFBVYkNvClNwamJFMVdmUjBpbVU0Z29DT1hy
            cG5QZTVxa0diZ2xHWW00cWRSZ3o3dzQKLS0tIGwrM0YyQTZ4UnVyTG5tdHp2azBh
            azhtbTJYZUFOOUc5cmhaQWtsS0xsVW8K0Ml7iVG07TmnJTsuDIWNCC28R33Ih1Q/
            FjH5pZAlh5WOSpXIwNImqDKgPdr0iwGJG5bE6GGKkZGitEoS00AzEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T14:39:52Z"
    mac: ENC[AES256_GCM,data:RdQLE+R4e++CJdqEzOFopp+Ki/SjH+iTGeDvHbheZ7eD5nIw1VvxMTxjiHl8/0JKpV8aetdXTrjtJa+n57epUJ8ZReX8YpEF5JbZ1HSzPrCjPm12GMvP+MpgacaIvaQx26WnEDSBHKuiiSW3UZ1PQzANSLceWU0mHPHADK4hIsM=,iv:90EygePn7tD0Ya4BpQsT+RXeXNYKdZYhHePxVHGQSwU=,tag:uOALJhSCCGfuD3v8rXPG2g==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
