apiVersion: v1
kind: Service
metadata:
  name: ping-pong-app-svc
  namespace: log-pong
spec:
  type: LoadBalancer
  selector:
    app: ping-pong-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000