apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-staging

resources:
  - ../../base

patches:
  - path: broadcaster-patch.yaml
  - path: todo-backend-patch.yaml

images:
  - name: BROADCASTER_IMAGE
    newName: europe-west3-docker.pkg.dev/dwk-gke-485813/todo-project/broadcaster
    newTag: staging-latest
  - name: TODO_APP_IMAGE
    newName: europe-west3-docker.pkg.dev/dwk-gke-485813/todo-project/todo-app
    newTag: staging-latest
  - name: TODO_BACKEND_IMAGE
    newName: europe-west3-docker.pkg.dev/dwk-gke-485813/todo-project/todo-backend
    newTag: staging-latest
  - name: TODO_JOB_IMAGE
    newName: europe-west3-docker.pkg.dev/dwk-gke-485813/todo-project/todo-cronjob
    newTag: staging-latest
