apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: todo-volume
          persistentVolumeClaim:
            claimName: todo-pvc
      containers:
        - name: todo-app
          image: zanaad/todo-app:latest
          volumeMounts:
            - name: todo-volume
              mountPath: /var/lib/data
          ports:
          - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: TODO_BACKEND_URL
              value: "http://todo-backend-svc:3000"
            - name: IMAGE_DIR
              value: "/var/lib/data"
            - name: CACHE_DURATION_MS
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: CACHE_DURATION_MS
            - name: IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: IMAGE_URL