apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: todo-pvc
  namespace: todo
spec:
  storageClassName: todo-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi