name: Build and Publish Ping Pong App

on:
  push:
    branches:
      - main
    paths:
      - 'ping-pong-app/**'
      - '.github/workflows/pingpong-gitops.yaml'

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push ping-pong-app
        run: |
          cd ping-pong-app
          docker build -t zanaad/ping-pong-app:${GITHUB_SHA} .
          docker push zanaad/ping-pong-app:${GITHUB_SHA}
      
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2
      
      - name: Update images
        run: |
          cd ping-pong-app/k8s
          kustomize edit set image PING_PONG_IMAGE=zanaad/ping-pong-app:${GITHUB_SHA}
      
      - name: Commit kustomization
        uses: EndBug/add-and-commit@v9
        with:
          add: 'ping-pong-app/k8s/kustomization.yaml'
          message: 'Update ping-pong images to ${{ github.sha }}'
          pull: '--rebase --autostash'
          default_author: github_actions