apiVersion: v1
kind: Secret
metadata:
    name: broadcaster-secret
type: Opaque
stringData:
    discord-webhook-url: ENC[AES256_GCM,data:na5fcG6IC3X1YZdHCOESLYjdVM2EgVHBZtSU0WyVXtFwDHIZklv70JtCgxUiSuoJ6fvdSzLF+DI34EBL0Q/naJMOa32PTT5snFoQrkS4s5QnMYlqB4eOPj/qfrynqknpYe5vR4FjHxd2/kHqs/0s1Bx5QOTuujFArQ==,iv:ua4DVINetbJjNqzRToKf2mbvnYjeh05ov7d/kDdkcHs=,tag:Dz3chpAiEwoHiA/uRxhorw==,type:str]
sops:
    age:
        - recipient: age1rkksvgwtq0jfyv5v98kz0md4emddt9u8xyprxzeqtkzskvqm83wql7lszx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySmo5ZkpIa3p1RmlacW4w
            NEk2Y1pRY0NzSWNQTkxuQTA3TDJLblFqRDBNClUxdEhYU2VGeTlrdExxNUJTVm85
            UmlPbjZvbnJybzhTYkU2MmdCVzlvTlUKLS0tIGN6M3B6cjdXZEh5S1VJT1ZnWG8y
            eGNDa2NaVkg5aUsrWFRvSzFmZkIxNUUKNdwKs9WJSPXiY9XlpdT1Jkf0IF7XlfMN
            0OqoMNVc0eaUUUQm33OKa2jIiP76hMaoE2fAxySc1F9rRjw3XV8YcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T18:57:53Z"
    mac: ENC[AES256_GCM,data:qpMW0wby6JT4V3KRixMei6v4RRhGA4FoZ5vmY3wp92ehFVro7TlVVkWKXrGeJCNZYPwJmaDTHzQf7FV75NiRw24Qq0Dd1Lxnaz6QTO5SLKFCiJ/3ZTMYy+UY441eHV6WWfJH9NdhWYu6ULhWOj9MGDFPgMAjIM+/sXIX82BDxKc=,iv:Isj2UANgY+LX3B/D5MpMKcDWuWjKP9KwOwh+M5LhvAU=,tag:fMlDk6SRjkKpsZeyCa9IRA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
